### ISSUE TITLE
Feature request: Detect a bad install of cloudflared

### ISSUE THREAD

**Issue by cacklinglaughing** [HttpRafa/Modflared#21]
**Is your feature request related to a problem? Please describe.**
So I just installed modflared, and it wouldn't work, some how, some way, the executable downloaded corrupted. I had to go to modflared/bin and delete the windows-amd64.exe, restart the game and everything worked perfect

**Describe the solution you'd like**
If this happens, just delete the executable and redownload it tbh

**Describe alternatives you've considered**
I can do this myself but someone not as tech-savvy may not be able to.

**Additional context**
This was the error I had:
```
Failed to start cloudflared: Cannot run program ""C:\Users\user\mmc-develop-win32\MultiMC\instances\1.20.4\.minecraft\modflared\bin\windows-amd64.exe"": CreateProcess error=193, %1 is not a valid Win32 application
java.io.IOException: Cannot run program ""C:\Users\user\mmc-develop-win32\MultiMC\instances\1.20.4\.minecraft\modflared\bin\windows-amd64.exe"": CreateProcess error=193, %1 is not a valid Win32 application
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1140) ~[?:?]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1074) ~[?:?]
	at de.rafael.modflared.tunnel.RunningTunnel.lambda$createTunnel$0(RunningTunnel.java:40) ~[modflared-1.1.0+beta.11.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
	at java.lang.ProcessImpl.create(Native Method) ~[?:?]
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:500) ~[?:?]
	at java.lang.ProcessImpl.start(ProcessImpl.java:159) ~[?:?]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1111) ~[?:?]
	... 5 more
```

**Comment by HttpRafa** [comment]
The question is whether it is possible to get a hash from Github with which you can verify the downloaded binary. But you could also run the file and see if the output is correct (which in my opinion is not a great idea).

**Comment by HttpRafa** [comment]
I added this feature today in this [commit](https://github.com/HttpRafa/modflared/commit/2418092c096949565eaa770c5cd527f6ef56339b). If you want, you are welcome to test it and report any bugs.
