### ISSUE TITLE
1.16.5 won't work most cases due to JDK 17

### ISSUE THREAD

**Issue by cacklinglaughing** [HttpRafa/Modflared#24]
**Describe the bug**
The latest version of modflared for 1.16.5, as of writing "1.2.0+release.23 for 1.16.5", won't run for Forge 1.16.5 in most cases because it was built with/uses JDK 17. Almost all mods for 1.16.5 use older Java versions (Java 8) and even Minecraft 1.16.5 itself doesn't run often with newer Java versions.

**Which version of the mod/game are you using?**
modflared 1.2.0+r23 Forge 1.16.5
Minecraft 1.16.5 + Forge

**To Reproduce**
1. Download mod
2. Run game

**Expected behavior**
Modflared for older versions should probably be compiled with their respective Java versions. 

**Screenshots**
None, log attached.

**Additional context**
```
ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 1.8.0_51 by Oracle Corporation
LEGACY JDK DETECTED, SECURED JAR HANDLING DISABLED
Added Lets Encrypt root certificates as additional trust
SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/user/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[java.lang.ThreadGroup:uncaughtException:1052]: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config modflared-common.mixins.json
[java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
[java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
[java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
[java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addConfig(MixinPlatformManager.java:262)
[java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformAgentDefault.prepare(MixinPlatformAgentDefault.java:46)
[java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinContainer.prepare(MixinContainer.java:122)
[java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.createContainerFor(MixinPlatformManager.java:144)
[java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addContainer(MixinPlatformManager.java:134)
[java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addNestedContainers(MixinPlatformManager.java:152)
[java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.scanForContainers(MixinPlatformManager.java:213)
[java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:186)
[java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
[java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)
[java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:195)
[java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
[java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler$$Lambda$459/1465606013.accept(Unknown Source)
[java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap.forEach(HashMap.java:1280)
[java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
[java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 1.8, ASM 9.1 (ASM10_EXPERIMENTAL))
[java.lang.ThreadGroup:uncaughtException:1061]: 	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570)
[java.lang.ThreadGroup:uncaughtException:1061]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:555)
[java.lang.ThreadGroup:uncaughtException:1061]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:500)
[java.lang.ThreadGroup:uncaughtException:1061]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:428)
[java.lang.ThreadGroup:uncaughtException:1061]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1285)
[java.lang.ThreadGroup:uncaughtException:1061]: 	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
[java.lang.ThreadGroup:uncaughtException:1061]: 	... 21 more

```

**Comment by HttpRafa** [comment]
Can't you change Java version to 17 in the launcher. I'll see if I can change the Java version to 8.

**Comment by HttpRafa** [comment]
The problem is that the toolchain we used doesn't support Java 8.

**Comment by cacklinglaughing** [comment]
Uh oh. That's a problem lol

I can change Java version to 17 but the issue with that is no other mods will load. Honestly, the game won't even load either half the time. I've had to give friends tech support getting modpacks set up for versions older than 1.18 and each time the issue was they were using Java 17 instead of Java 8. I wish this wasn't the case, but TONS of errors appear when you try to use modern Java with 1.16.5: https://www.reddit.com/r/feedthebeast/comments/11epgn7/what_java_version_do_i_need_to_run_a_1165_forge/ https://forums.minecraftforge.net/topic/123732-solved-losing-my-mind-over-forge-server-installation/

**Comment by HttpRafa** [comment]
I found the solution to the toolchain problem (I had to change 1line :)). I ported the mod to Java 8 so it should only need Java 8 in the latest 1.16.5 build. [Download](https://modrinth.com/mod/modflared/version/OwgQEgzO)

**Comment by cacklinglaughing** [comment]
I just realized I never got back to you here, it seems to be working with Java 8 now thanks!
